<a href="https://colab.research.google.com/github/saik2300/webscraping/blob/main/webscraping2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
url = 'https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area'
page = requests.get(url)

soup = BeautifulSoup(page.text, 'html')

In [ ]:
tables = soup.find_all('table')[1]

In [ ]:
print(tables)

<table class="wikitable sortable sticky-header col2left col4left" style="text-align:right">
<tbody><tr>
<th>Rank
</th>
<th>State /<br/>Union Territory
</th>
<th class="data-sort-type:number">Area (km<sup>2</sup>)
</th>
<th>Region
</th>
<th>%<br/>total
</th>
<th>
</th></tr>
<tr>
<td>1 (S1)
</td>
<td><a href="/wiki/Rajasthan" title="Rajasthan">Rajasthan</a>
</td>
<td>342,239
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>10.411
</td>
<td>
</td></tr>
<tr>
<td>2 (S2)
</td>
<td><a href="/wiki/Madhya_Pradesh" title="Madhya Pradesh">Madhya Pradesh</a>
</td>
<td>308,252
</td>
<td><a href="/wiki/Central_India" title="Central India">Central</a>
</td>
<td>9.377
</td>
<td><sup class="reference" id="cite_ref-MP-CH_4-0"><a href="#cite_note-MP-CH-4"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>3 (S3)
</td>
<td><a href="/wiki/Maharashtra" title="Maharashtra">Maharashtra</a>
</td>
<td>307,713
</td>
<td><a href="/wiki/Western_India" title="Western India">Western</a>
</td>
<td>9.360
</td>
<td>
</td></tr>
<tr>
<td>4 (S4)
</td>
<td><a href="/wiki/Uttar_Pradesh" title="Uttar Pradesh">Uttar Pradesh</a>
</td>
<td>240,928
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>7.329
</td>
<td>
</td></tr>
<tr>
<td>5 (S5)
</td>
<td><a href="/wiki/Gujarat" title="Gujarat">Gujarat</a>
</td>
<td>196,024
</td>
<td><a href="/wiki/Western_India" title="Western India">Western</a>
</td>
<td>5.963
</td>
<td>
</td></tr>
<tr>
<td>6 (S6)
</td>
<td><a href="/wiki/Karnataka" title="Karnataka">Karnataka</a>
</td>
<td>191,791
</td>
<td><a href="/wiki/South_India" title="South India">Southern</a>
</td>
<td>5.834
</td>
<td>
</td></tr>
<tr>
<td>7 (S7)
</td>
<td><a href="/wiki/Andhra_Pradesh" title="Andhra Pradesh">Andhra Pradesh</a>
</td>
<td>162,975
</td>
<td><a href="/wiki/South_India" title="South India">Southern</a>
</td>
<td>4.957
</td>
<td><sup class="reference" id="cite_ref-P-AP_6-0"><a href="#cite_note-P-AP-6"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>8 (S8)
</td>
<td><a href="/wiki/Odisha" title="Odisha">Odisha</a>
</td>
<td>155,707
</td>
<td><a class="mw-redirect" href="/wiki/Eastern_India" title="Eastern India">Eastern</a>
</td>
<td>4.7361
</td>
<td>
</td></tr>
<tr>
<td>9 (S9)
</td>
<td><a href="/wiki/Chhattisgarh" title="Chhattisgarh">Chhattisgarh</a>
</td>
<td>135,192
</td>
<td><a class="mw-redirect" href="/wiki/Central_india" title="Central india">Central</a>
</td>
<td>4.112
</td>
<td><sup class="reference" id="cite_ref-MP-CH_4-1"><a href="#cite_note-MP-CH-4"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>10 (S10)
</td>
<td><a href="/wiki/Tamil_Nadu" title="Tamil Nadu">Tamil Nadu</a>
</td>
<td>130,058
</td>
<td><a href="/wiki/South_India" title="South India">Southern</a>
</td>
<td>3.956
</td>
<td>
</td></tr>
<tr>
<td>11 (S11)
</td>
<td><a href="/wiki/Telangana" title="Telangana">Telangana</a>
</td>
<td>112,077
</td>
<td><a class="mw-redirect" href="/wiki/South_india" title="South india">Southern</a>
</td>
<td>3.409
</td>
<td>
</td></tr>
<tr>
<td>12 (S12)
</td>
<td><a href="/wiki/Bihar" title="Bihar">Bihar</a>
</td>
<td>94,163
</td>
<td><a href="/wiki/East_India" title="East India">Eastern</a>
</td>
<td>2.864
</td>
<td>
</td></tr>
<tr>
<td>13 (S13)
</td>
<td><a href="/wiki/West_Bengal" title="West Bengal">West Bengal</a>
</td>
<td>88,752
</td>
<td><a href="/wiki/East_India" title="East India">Eastern</a>
</td>
<td>2.740
</td>
<td>
</td></tr>
<tr>
<td>14 (S14)
</td>
<td><a href="/wiki/Arunachal_Pradesh" title="Arunachal Pradesh">Arunachal Pradesh</a>
</td>
<td>83,743
</td>
<td><a href="/wiki/Northeast_India" title="Northeast India">Northeastern</a>
</td>
<td>2.547
</td>
<td>
</td></tr>
<tr>
<td>15 (S15)
</td>
<td><a href="/wiki/Jharkhand" title="Jharkhand">Jharkhand</a>
</td>
<td>79,716
</td>
<td><a href="/wiki/East_India" title="East India">Eastern</a>
</td>
<td>2.424
</td>
<td>
</td></tr>
<tr>
<td>16 (S16)
</td>
<td><a href="/wiki/Assam" title="Assam">Assam</a>
</td>
<td>78,438
</td>
<td><a href="/wiki/Northeast_India" title="Northeast India">Northeastern</a>
</td>
<td>2.386
</td>
<td>
</td></tr>
<tr>
<td>17 (UT1)
</td>
<td><a href="/wiki/Ladakh" title="Ladakh">Ladakh</a>
</td>
<td>59,146<br/>(166,698)
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>1.799<br/>(5.071)
</td>
<td><sup class="reference" id="cite_ref-7"><a href="#cite_note-7"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>18 (S17)
</td>
<td><a href="/wiki/Himachal_Pradesh" title="Himachal Pradesh">Himachal Pradesh</a>
</td>
<td>55,673
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>1.693
</td>
<td>
</td></tr>
<tr>
<td>19 (S18)
</td>
<td><a href="/wiki/Uttarakhand" title="Uttarakhand">Uttarakhand</a>
</td>
<td>53,483
</td>
<td><a class="mw-redirect" href="/wiki/Northwestern_India" title="Northwestern India">Northern</a>
</td>
<td>1.626
</td>
<td>
</td></tr>
<tr>
<td>20 (S19)
</td>
<td><a href="/wiki/Punjab,_India" title="Punjab, India">Punjab</a>
</td>
<td>50,362
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>1.532
</td>
<td>
</td></tr>
<tr>
<td>21 (S20)
</td>
<td><a href="/wiki/Haryana" title="Haryana">Haryana</a>
</td>
<td>44,212
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>1.344
</td>
<td>
</td></tr>
<tr>
<td>22 (UT2)
</td>
<td><a href="/wiki/Jammu_and_Kashmir_(union_territory)" title="Jammu and Kashmir (union territory)">Jammu and Kashmir</a>
</td>
<td>42,241<br/>(55,538)
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>1.284<br/>(1.689)
</td>
<td><sup class="reference" id="cite_ref-8"><a href="#cite_note-8"><span class="cite-bracket">[</span>d<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>23 (S21)
</td>
<td><a href="/wiki/Kerala" title="Kerala">Kerala</a>
</td>
<td>38,863
</td>
<td><a href="/wiki/South_India" title="South India">Southern</a>
</td>
<td>1.182
</td>
<td>
</td></tr>
<tr>
<td>24 (S22)
</td>
<td><a href="/wiki/Meghalaya" title="Meghalaya">Meghalaya</a>
</td>
<td>22,429
</td>
<td><a href="/wiki/Northeast_India" title="Northeast India">Northeastern</a>
</td>
<td>0.682
</td>
<td>
</td></tr>
<tr>
<td>25 (S23)
</td>
<td><a href="/wiki/Manipur" title="Manipur">Manipur</a>
</td>
<td>22,327
</td>
<td><a href="/wiki/Northeast_India" title="Northeast India">Northeastern</a>
</td>
<td>0.679
</td>
<td>
</td></tr>
<tr>
<td>26 (S24)
</td>
<td><a href="/wiki/Mizoram" title="Mizoram">Mizoram</a>
</td>
<td>21,081
</td>
<td><a href="/wiki/Northeast_India" title="Northeast India">Northeastern</a>
</td>
<td>0.641
</td>
<td>
</td></tr>
<tr>
<td>27 (S25)
</td>
<td><a href="/wiki/Nagaland" title="Nagaland">Nagaland</a>
</td>
<td>16,579
</td>
<td><a href="/wiki/Northeast_India" title="Northeast India">Northeastern</a>
</td>
<td>0.504
</td>
<td>
</td></tr>
<tr>
<td>28 (S26)
</td>
<td><a href="/wiki/Tripura" title="Tripura">Tripura</a>
</td>
<td>10,491
</td>
<td><a href="/wiki/Northeast_India" title="Northeast India">Northeastern</a>
</td>
<td>0.319
</td>
<td>
</td></tr>
<tr>
<td>29 (UT3)
</td>
<td><a href="/wiki/Andaman_and_Nicobar_Islands" title="Andaman and Nicobar Islands">Andaman and Nicobar Islands</a>
</td>
<td>8,249
</td>
<td><a href="/wiki/Bay_of_Bengal" title="Bay of Bengal">Bay of Bengal</a>
</td>
<td>0.250
</td>
<td>
</td></tr>
<tr>
<td>30 (S27)
</td>
<td><a href="/wiki/Sikkim" title="Sikkim">Sikkim</a>
</td>
<td>7,096
</td>
<td><a href="/wiki/Northeast_India" title="Northeast India">Northeastern</a>
</td>
<td>0.215
</td>
<td>
</td></tr>
<tr>
<td>31 (S28)
</td>
<td><a href="/wiki/Goa" title="Goa">Goa</a>
</td>
<td>3,702
</td>
<td><a href="/wiki/Western_India" title="Western India">Western</a>
</td>
<td>0.112
</td>
<td>
</td></tr>
<tr>
<td>32 (UT4)
</td>
<td>National Capital Territory–Delhi
</td>
<td>1,484
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>0.045
</td>
<td>
</td></tr>
<tr>
<td>33 (UT5)
</td>
<td><a href="/wiki/Dadra_and_Nagar_Haveli_and_Daman_and_Diu" title="Dadra and Nagar Haveli and Daman and Diu">Dadra and Nagar Haveli and Daman and Diu</a>
</td>
<td>603
</td>
<td><a href="/wiki/Western_India" title="Western India">Western</a>
</td>
<td>0.018
</td>
<td><sup class="reference" id="cite_ref-auto2_9-0"><a href="#cite_note-auto2-9"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>34 (UT6)
</td>
<td><a href="/wiki/Puducherry_(union_territory)" title="Puducherry (union territory)">Puducherry</a>
</td>
<td>479
</td>
<td><a href="/wiki/South_India" title="South India">Southern</a>
</td>
<td>0.014
</td>
<td><sup class="reference" id="cite_ref-P-AP_6-1"><a href="#cite_note-P-AP-6"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a></sup>
</td></tr>
<tr>
<td>35 (UT7)
</td>
<td><a href="/wiki/Chandigarh" title="Chandigarh">Chandigarh</a>
</td>
<td>114
</td>
<td><a href="/wiki/North_India" title="North India">Northern</a>
</td>
<td>0.003
</td>
<td>
</td></tr>
<tr>
<td>36 (UT8)
</td>
<td><a href="/wiki/Lakshadweep" title="Lakshadweep">Lakshadweep</a>
</td>
<td>32
</td>
<td><a href="/wiki/Arabian_Sea" title="Arabian Sea">Arabian Sea</a>
</td>
<td>0.001
</td>
<td>
</td></tr>
<tr>
<td>
</td>
<td><b>India</b>
</td>
<td>3,166,414<br/>(3,287,263)<sup class="reference" id="cite_ref-11"><a href="#cite_note-11"><span class="cite-bracket">[</span>e<span class="cite-bracket">]</span></a></sup>
</td>
<td>
</td>
<td>96.323<br/>(100)
</td>
<td>
</td></tr></tbody></table>

In [ ]:
state_titles = tables.find_all('th')

In [ ]:
print(state_titles)

[<th>Rank
</th>, <th>State /<br/>Union Territory
</th>, <th class="data-sort-type:number">Area (km<sup>2</sup>)
</th>, <th>Region
</th>, <th>%<br/>total
</th>, <th>
</th>]

In [ ]:
import re
statet = [titles.text.strip() for titles in state_titles]
cleaned_column_names = statet[0:4]
print(cleaned_column_names)

['Rank', 'State /Union Territory', 'Area (km2)', 'Region']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(columns = cleaned_column_names)

In [ ]:
table_data = tables.find_all('tr')

In [ ]:
for row in table_data[1:]:
  row_data = row.find_all('td')
  individual_row_data = [data.text.strip() for data in row_data]
  individual = [re.sub(r'\([A-Z][A-Z]?[0-9]+\)','',ro) for ro in individual_row_data]
  inserted_data = individual[0:4]
  length = len(df)
  df.loc[length] = inserted_data

In [ ]:
df

,Rank,State /Union Territory,Area (km2),Region
0,1,Rajasthan,"342,239",Northern
1,2,Madhya Pradesh,"308,252",Central
2,3,Maharashtra,"307,713",Western
3,4,Uttar Pradesh,"240,928",Northern
4,5,Gujarat,"196,024",Western
5,6,Karnataka,"191,791",Southern
6,7,Andhra Pradesh,"162,975",Southern
7,8,Odisha,"155,707",Eastern
8,9,Chhattisgarh,"135,192",Central
9,10,Tamil Nadu,"130,058",Southern
10,11,Telangana,"112,077",Southern
11,12,Bihar,"94,163",Eastern
12,13,West Bengal,"88,752",Eastern
13,14,Arunachal Pradesh,"83,743",Northeastern
14,15,Jharkhand,"79,716",Eastern
15,16,Assam,"78,438",Northeastern
16,17,Ladakh,"59,146(166,698)",Northern
17,18,Himachal Pradesh,"55,673",Northern
18,19,Uttarakhand,"53,483",Northern
19,20,Punjab,"50,362",Northern
20,21,Haryana,"44,212",Northern
21,22,Jammu and Kashmir,"42,241(55,538)",Northern
22,23,Kerala,"38,863",Southern
23,24,Meghalaya,"22,429",Northeastern
24,25,Manipur,"22,327",Northeastern
25,26,Mizoram,"21,081",Northeastern
26,27,Nagaland,"16,579",Northeastern
27,28,Tripura,"10,491",Northeastern
28,29,Andaman and Nicobar Islands,"8,249",Bay of Bengal
29,30,Sikkim,"7,096",Northeastern
30,31,Goa,"3,702",Western
31,32,National Capital Territory–Delhi,"1,484",Northern
32,33,Dadra and Nagar Haveli and Daman and Diu,603,Western
33,34,Puducherry,479,Southern
34,35,Chandigarh,114,Northern
35,36,Lakshadweep,32,Arabian Sea
36,,India,"3,166,414(3,287,263)[e]",

In [ ]:
df = df.drop(index=36)

In [ ]:
df.to_csv(r'/content/drive/MyDrive/cleaned_datase/States.csv',index=False)